// Google Drive drill library integration.
//
// Folder structure expected in Drive:
//   <DRIVE_FOLDER_ID> (root)
//   ├── Shooting/
//   │   ├── Beginner/   ← video files here
//   │   ├── Intermediate/
//   │   └── Expert/
//   ├── Dribbling/
//   │   ├── Beginner/
//   │   ├── Intermediate/
//   │   └── Expert/
//   └── Conditioning/   (any category name is fine)
//
// Required env vars:
//   GOOGLE_SERVICE_ACCOUNT_EMAIL
//   GOOGLE_PRIVATE_KEY          (the -----BEGIN PRIVATE KEY----- block, newlines as \n)
//   GOOGLE_DRIVE_FOLDER_ID      (ID of the root drills folder)

export type DrillFile = {
  id: string;
  name: string;
  // Embed URL for <video> or <iframe> — works when file is shared with service account
  embedUrl: string;
  // Thumbnail (auto-generated by Drive for video files)
  thumbnailUrl: string | null;
  mimeType: string;
};

export type DrillTier = {
  tier: string;
  drills: DrillFile[];
};

export type DrillCategory = {
  category: string;
  tiers: DrillTier[];
};

// Drive REST API — uses a JWT service account token, no sdk dep needed.
// If you later install `googleapis` you can swap this for the SDK.

async function getAccessToken(): Promise<string> {
  const email = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
  const rawKey = process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n");
  if (!email || !rawKey) throw new Error("Missing GOOGLE_SERVICE_ACCOUNT_EMAIL or GOOGLE_PRIVATE_KEY");

  const now = Math.floor(Date.now() / 1000);
  const header = { alg: "RS256", typ: "JWT" };
  const payload = {
    iss: email,
    scope: "https://www.googleapis.com/auth/drive.readonly",
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now,
  };

  function b64(obj: object) {
    return Buffer.from(JSON.stringify(obj)).toString("base64url");
  }

  // Build unsigned JWT
  const unsigned = `${b64(header)}.${b64(payload)}`;

  // Sign with RS256 using Web Crypto
  const keyData = rawKey
    .replace("-----BEGIN PRIVATE KEY-----", "")
    .replace("-----END PRIVATE KEY-----", "")
    .replace(/\s/g, "");
  const binaryKey = Buffer.from(keyData, "base64");
  const cryptoKey = await crypto.subtle.importKey(
    "pkcs8", binaryKey,
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false, ["sign"]
  );
  const sig = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5", cryptoKey,
    new TextEncoder().encode(unsigned)
  );
  const jwt = `${unsigned}.${Buffer.from(sig).toString("base64url")}`;

  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer", assertion: jwt }),
    next: { revalidate: 3500 },
  });
  const json = await res.json();
  if (!json.access_token) throw new Error(`Drive auth failed: ${JSON.stringify(json)}`);
  return json.access_token;
}

async function listChildren(folderId: string, token: string): Promise<any[]> {
  const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
    `'${folderId}' in parents and trashed = false`
  )}&fields=files(id,name,mimeType,thumbnailLink)&orderBy=name&pageSize=200`;
  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` },
    next: { revalidate: 300 }, // cache 5 minutes
  });
  const json = await res.json();
  return json.files ?? [];
}

export async function getDrillLibrary(): Promise<DrillCategory[]> {
  const rootId = process.env.GOOGLE_DRIVE_FOLDER_ID;
  if (!rootId) return [];

  let token: string;
  try {
    token = await getAccessToken();
  } catch {
    return [];
  }

  const FOLDER = "application/vnd.google-apps.folder";
  const categories: DrillCategory[] = [];

  const categoryFolders = (await listChildren(rootId, token)).filter((f) => f.mimeType === FOLDER);

  for (const cat of categoryFolders) {
    const tierFolders = (await listChildren(cat.id, token)).filter((f) => f.mimeType === FOLDER);
    const tiers: DrillTier[] = [];

    for (const tier of tierFolders) {
      const files = (await listChildren(tier.id, token)).filter((f) => f.mimeType !== FOLDER);
      const drills: DrillFile[] = files.map((f) => ({
        id: f.id,
        name: f.name.replace(/\.[^.]+$/, ""), // strip extension for display
        embedUrl: `https://drive.google.com/file/d/${f.id}/preview`,
        thumbnailUrl: f.thumbnailLink ?? null,
        mimeType: f.mimeType,
      }));
      if (drills.length > 0) tiers.push({ tier: tier.name, drills });
    }
    if (tiers.length > 0) categories.push({ category: cat.name, tiers });
  }

  return categories;
}
